### ISSUE TITLE
word_all에서 reported값의 존재 의미

### ISSUE THREAD

**Issue by MerHS** [MerHS/pylimedict#6]
reported값은 현재 그 word에 대한 신고 수를 표시하는데, 사실 report_log 테이블에 의해 나오는 derived attribute라 굳이 따로 attribute로 있을 필요가 있나 싶기도 하고 해서 이 값을 뽑아오기 좀 나아보이는 방법을 생각해봅시다.

**Comment by iKoru** [comment]
일단 단어를 검색할때 신고 개수를 표시해줘야 할 필요가 있는지부터 정해야될 것 같아요
1) 표시해야한다면 테이블에서 뺄 경우에는 이를 위해 조인을 한 번 더 해야되니까, 그러느니 attribute로 보존하고 새로운 report insert할 때 쿼리를 한번 더 실행해서 트랜잭션으로 처리하는 식으로 하면 될거같습니다.
2) 표시할 필요가 없다면 명백히 빼도 될 사항인 것 같습니다.

근데 전 딱히 표시할 필요가 있나 싶네요.

**Comment by MerHS** [comment]
일단 표시는 안하기로 하고 reported값은 admin에서 신고목록 소팅하는데 쓰이므로 일단 놔두죠.
